apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.11.3
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: true
        adminPassword: "Passw0rd999!"
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:

              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true

              - name: K10-Prometheus
                type: prometheus
                url: http://prometheus-server.kasten-io/k10/prometheus/
                access: proxy
                editable: false
                jsonData:
                  timeInterval: 1m

              - name: InfluxDB
                type: influxdb
                url: http://influxdb-influxdb2.monitoring.svc.cluster.local:80
                access: proxy
                isDefault: false
                jsonData:
                  organization: "influxdata"
                  defaultBucket: "veeam"
                  version: "Flux"
                secureJsonData:
                  token: "97RCYTlnEfgl67xI6E3gIfU75j9Pk37w"

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:

            kubernetes:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/kubernetes-dashboard.yaml

            proxmox:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/proxmox-dashboard.yaml

            veeam-dashboard:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/veeam-dashboard.yaml

            veeam-kasten-dashboard:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/veeam-kasten.yaml

            vsphere-telegraf-dashboard:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/vsphere-telegraf-dashboard.yaml
            
            vsphere-telegraf-datastore:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/vsphere-telegraf-datastore.yaml

            vsphere-telegraf-hosts:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/vsphere-telegraf-hosts.yaml

            vsphere-telegraf-vms:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/grafana-dashboards/vsphere-telegraf-vms.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true