apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelCade/UpTheStack-ArgoCD.git
    targetRevision: main
    path: apps/argocd-apps
    helm:
      valueFiles:
        - ../monitoring/grafana-values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
