apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.11.3
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: true
        env:
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegraf-influx-token
                key: influx-token
                    - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-admin-secret
                key: admin-password
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:

              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true

              - name: K10-Prometheus
                type: prometheus
                url: http://prometheus-server.kasten-io/k10/prometheus/
                access: proxy
                editable: false
                jsonData:
                  timeInterval: 1m

              - name: InfluxDB
                type: influxdb
                url: http://influxdb-influxdb2.monitoring.svc.cluster.local:80
                access: proxy
                isDefault: false
                jsonData:
                  organization: "influxdata"
                  defaultBucket: "veeam"
                  version: "Flux"
                  token:  "${INFLUX_TOKEN}"

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:

            kubernetes:
              gnetId: 10000
              revision: 1
              datasource: Prometheus

            veeam-dashboard:
              url: https://raw.githubusercontent.com/MichaelCade/UpTheStack-ArgoCD/refs/heads/main/apps/argocd-apps/veeam-dashboard.yaml

            k10-dashboard:
              gnetId: 21065
              revision: 1
              datasource:
                - name: DS_PROMETHEUS
                  value: Prometheus
                - name: VAR_CLUSTER
                  value: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true