apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.11.3
    helm:
      values: |
        service:
          type: LoadBalancer
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:

              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy

              - name: InfluxDB
                type: influxdb
                url: http://influxdb-influxdb2.monitoring.svc.cluster.local:80
                access: proxy
                isDefault: true
                jsonData:
                  organization: "influxdata"
                  defaultBucket: "veeam" 
                  version: "Flux"
                secureJsonData:
                  token: "97RCYTlnEfgl67xI6E3gIfU75j9Pk37w"

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:

            kubernetes:
              gnetId: 10000
              revision: 1
              datasource: Prometheus

            veeam-dashboard:
              gnetId: 18854
              revision: 6
              datasource: InfluxDB
              postProcess: | 
                sed 's/\${DS_INFLUXDB}/InfluxDB/g'
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true