apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.influxdata.com/
    chart: influxdb2
    targetRevision: 2.1.2
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
        adminUser:
          enabled: true
          username: admin
          password: Passw0rd999! # Replace with a secure password
        auth:
          enabled: true
        service: 
          type: LoadBalancer
          port: 80 
          portName: http
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
        initScripts:
          enabled: true
          scripts:
            create-bucket.sh: |
              #!/bin/bash
              influx bucket create \
                -n veeam \
                -o "influxdata" \
                -r 0 # Retention period of 0 means infinite retention