apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-nfs
  namespace: argocd
spec:
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/MichaelCade/UpTheStack-ArgoCD.git
    path: apps/kasten-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
