apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perses
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://perses.github.io/helm-charts
    chart: perses
    targetRevision: 0.13.1
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          size: 10Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true