apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelCade/UpTheStack-ArgoCD.git
    targetRevision: main
    # This should be the path to the folder where your Argo CD application manifests are.
    # Since your application manifests are in `apps/argocd-apps`, this should point to `apps/argocd-apps`, and
    # Argo CD will fetch the manifest from there.
    path: apps/argocd-apps  # Directory containing your Argo CD application manifests (prometheus-app.yaml, etc.)
    helm:
      chart: prometheus-community/kube-prometheus-stack  # The remote Helm chart you want to use
      repoURL: https://prometheus-community.github.io/helm-charts  # Remote Helm chart repository
      valueFiles:
        - ./monitoring/prometheus-values.yaml  # Path to the values file relative to the root of the repository
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
