apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelCade/UpTheStack-ArgoCD.git
    targetRevision: main
    path: apps/monitoring  # Correct path to Prometheus values
    helm:
      chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      valueFiles:
        - prometheus-values.yaml  # Ensure this file exists and is valid
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true