apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.influxdata.com/
    chart: telegraf
    targetRevision: 1.8.56
    helm:
      values: |
        config:
          influxdb2Url: "http://influxdb-influxdb2.monitoring.svc.cluster.local:80"
        telegraf:
          args:
          - "--config"
          - "/etc/telegraf-generated/telegraf-generated.conf"
          config:
            outputs:
              - influxdb_v2:
                  urls: ["http://influxdb-influxdb2.monitoring.svc.cluster.local:80"]
                  insecure_skip_verify: false
                  token: "${INFLUX_TOKEN}"  # Use the token from the secret
                  organization: "influxdata"
                  bucket: "veeam"
            inputs: []  # Add specific inputs if needed
            processors: []  # Add specific processors if needed
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "350Mi"
              cpu: "50m"
          rbac:
            clusterWide: true
          env:
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegraf-influx-token
                key: influx-token
          service:
            enabled: false
          tplVersion: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true