apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: ollama-models-pvc
      initContainers:
        - name: model-downloader
          image: ollama/ollama:latest
          command: ["/bin/sh", "-c", "ollama pull mistral"]
          volumeMounts:
            - mountPath: /root/.ollama/models
              name: models-storage
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          volumeMounts:
            - mountPath: /root/.ollama/models
              name: models-storage
