apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: nfs-export-profile
  namespace: kasten-io
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: kasten-nfs-pvc
      path: /mnt/nfs
  type: Location
