apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: nfs-export-profile
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    type: NFS
    nfs:
      path: /mnt/nfs
      server: 192.168.169.2
