installCRDs: true
replicaCount: 2
webhook:
  replicaCount: 2
cainjector:
  replicaCount: 2
extraArgs:
  - --enable-certificate-owner-ref=true
nodeSelector:
  kubernetes.io/os: linux
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - operator: "Exists"
